### ISSUE TITLE
API for an unknown number of errors

### ISSUE THREAD

**Issue by J7mbo** [hashicorp/go-multierror#21]
There are many cases where a call to some library returns `[]error`. 

Given this use case, utilising `go-multierror` is problematic as the client must check for an initial error, and if there are any remaining, _then_ use `Append`.

This proposal removes this requirement from the client and adds an alternative (non-BC breaking) API change to allow a list of errors to be given.

Proposed signature:

`AppendList(errs ...[]error)`

All functionality would be identical, except that providing no errors would return an empty `Error`.

**Comment by mitchellh** [comment]
I usually do `multierror.Append(nil, errs...)`. 

Is there a reason this isn't ideal in this scenario?

**Comment by J7mbo** [comment]
@mitchellh I missed this, and that is indeed ideal. Many thanks!
