### ISSUE TITLE
A new release with Group

### ISSUE THREAD

**Issue by Flygrounder** [hashicorp/go-multierror#29]
Can you make a new release, including Group in order to make it available in go modules? It is already  present in your documentation, so I think, that it is reasonable to include it in a new release.

**Comment by jefferai** [comment]
Until that happens you can use @master to pull in the current head commit,

**Comment by nono** [comment]
v1.1.0 was released with Group: https://github.com/hashicorp/go-multierror/releases/tag/v1.1.0
