### ISSUE TITLE
Marshalling multierror

### ISSUE THREAD

**Issue by malpiatko** [hashicorp/go-multierror#3]
Hey,

I am using your multierror package in my project however I need to wrap it and add a MarshalJSON as it doesn't Marshal out of the box (because of the Func field). Would it be ok to add it to your project? In my case it would just marshal the error array. I don't know if you would want to do something more elaborate

**Comment by mitchellh** [comment]
Sounds good to me. I commented on your PR, if we can unmarshal then I think its fine!

**Comment by malpiatko** [comment]
I changed the code and answered your suggestions :)

**Comment by ConradIrwin** [comment]
@mitchellh Another attempt here: https://github.com/hashicorp/go-multierror/pull/15

The problem I was trying to solve was just that it fails, but adding a round-trip does seem kind of handy, so done.
