### ISSUE TITLE
errors.As and errors.Is are not supported in errors package 

### ISSUE THREAD

**Issue by lily1110** [hashicorp/go-multierror#36]
When I update this package
`go get -u  github.com/hashicorp/go-multierror
`
It was failed.
`# github.com/hashicorp/go-multierror`
`../../hashicorp/go-multierror/multierror.go:112:9: undefined: errors.As`
`../../hashicorp/go-multierror/multierror.go:117:9: undefined: errors.Is`

The As and Is are not in the `errors` package.
Go SDK: 1.10.2

**Comment by mitchellh** [comment]
That Go version is outdated. Please stick to a prior version of this lib. The errors introduction was Go 1.13 which is already N-1.
