### ISSUE TITLE
Returning nil values from Append

### ISSUE THREAD

**Issue by buth** [hashicorp/go-multierror#42]
At the moment, Append never returns nil. The use case I've run across is the following, where a function returns an array of errors, and it's necessary to return an error if any of them are non-nil.

```go
result, errs := multierrorFunc()
if err := multierror.Append(nil, errs...); err != nil {
	return err
}
```

I think all that would be needed is to add a check for the length of the error list and update [this test](https://github.com/hashicorp/go-multierror/blob/3df56f46554f149c736e0b4498f092f05cc8ca6f/append_test.go#L59-L66).

```go
if len(err.Errors) == 0 {
	return nil
}
```

If this seems like non-breaking functionality that would be useful, I could submit a pull request.

Thanks all!

**Comment by mitchellh** [comment]
This is what the `ErrorOrNil` func is for: https://pkg.go.dev/github.com/hashicorp/go-multierror#Error.ErrorOrNil
