### ISSUE TITLE
multierror undefined errors.AS errors.Is

### ISSUE THREAD

**Issue by dschere** [hashicorp/go-multierror#46]
go get github.com/hashicorp/go-multierror  
# github.com/hashicorp/go-multierror
../go/src/github.com/hashicorp/go-multierror/multierror.go:112:9: undefined: errors.As
../go/src/github.com/hashicorp/go-multierror/multierror.go:117:9: undefined: errors.Is

go version 
   go1.10.4 linux/amd64

**Comment by mwhooker** [comment]
Thanks for the report, @dschere.

This package uses features that require at least version 1.13 of go. If you're not able to update your go version for some reason, the tagged [v1.0.0](https://github.com/hashicorp/go-multierror/tree/v1.0.0) version of this package should continue to work for you.

We have an open ticket to add this to the documentation, so I will close this so we can track it there.
